
import Head from 'next/head'
import { Box, Flex, Text } from '@chakra-ui/react';
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from './header'
import Navigation from './navigation'
import Dashboard from './Dashboard/dashboard'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Box>
      <Header />
      <Navigation />
      <Dashboard />
     </Box>
    </Box>
  )
}
